### ISSUE TITLE
LGPL/AGPL violations

### ISSUE THREAD

**Issue by prusnak** [monero-project/kastelo#28] opened 2018-09-10 14:13 UTC
1) directory `firmware/monezor` contains Trezor code, which is LGPLv3 licensed, yet there is no COPYING file included in the directory. I suggest to add https://github.com/trezor/trezor-mcu/blob/master/COPYING file into this directory.

2) directory `hardware/monezor` contains designs based on Trezor design, which is AGPLv3 licensed. Via the nature of this license all files based on this design should be also AGPLv3 licensed. I suggest to add https://github.com/trezor/trezor-hw/blob/master/COPYING into this directory.

**Comment by michaesc** [comment] 2018-10-05 09:12
Hi Stick, thanks for noticing the missing COPYING file and good suggestion. The problem is now fixed in https://github.com/monero-project/kastelo/commit/1fe6d28

To determine if and where there is a hardware design license collision, please provide the AGPLv3 licensed source (not manufacturing) files for the schematic, BOM, and layout corresponding to our Monezor design. Monezor incorporates USB-C technology, so I'm assuming you are referring to the Trezor Model T design in your license comment number two.

**Comment by prusnak** [comment] 2018-10-05 11:12
Thanks for fixing the first issue.

As for the second issue, no, I am talking about Trezor One design. It is available from https://github.com/trezor/trezor-hw/ repo which is AGPLv3 licensed. Your design in `hardware/monezor` is clearly based on that particular design. Combination of usage STM32F205RET6 and MCP1703 clearly gives that fact away. We don't use these components in Trezor Model T. Further inspection of [monezor.csv](https://github.com/monero-project/kastelo/blob/master/hardware/monezor/BOM/monezor.csv) with [trezor_v1.1_BOM.csv](https://github.com/trezor/trezor-hw/blob/master/electronics/trezor_v1.1_BOM.csv) shows more-or-less the same analog components (resistors, capacitors) confirming the fact monezor is a fork of Trezor One hardware.

**Comment by michaesc** [comment] 2018-12-31 17:30
As suggested, a COPYING file including AGPLv3 text was added in commit f705d85.

**Closed as completed by michaesc** 2018-12-31 17:30 UTC
